sudo: required
services:
  - docker
language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "0.10"
  - "0.12"
  - "1"
  - "2"
  - "3"
  - "4"

addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - libpango1.0-dev
      - libgif-dev
env: CXX="g++-4.8" CC="gcc-4.8"

script: "npm run-script travis"
after_success: "<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"
