services:
  - docker
language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "8"
  - "10"
  - "node"

script: "npm run-script travis"
after_success: "<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"
