language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "0.8"
  - "0.10"
before_install: "sudo apt-get update && sudo apt-get install -y libcairo2-dev libjpeg8-dev libgif-dev && npm install -g npm && npm cache clean"
script: "npm run-script travis"

after_success: "<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"
